ActivityManager.Web/Models/Activity.cs
using System.ComponentModel.DataAnnotations;

namespace ActivityManager.Web.Models
{
    public class Activity
    {
        public Guid Id { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public double? Duration { get; set; }
        public string? Note { get; set; }
        public bool IsSaved { get; set; }
        public Guid ActivityTypeId { get; set; }
        public ActivityType ActivityType { get; set; } = null!;
    }
}

ActivityManager.Web/Models/ActivityModel.cs
using System.ComponentModel.DataAnnotations;

namespace ActivityManager.Web.Models
{
    public class ActivityModel
    {
        public Guid Id { get; set; }
        [Required] public string? StartTime { get; set; }
        public string? EndTime { get; set; }
        public double? Duration { get; set; }
        public string? Note { get; set; }
    }
}

ActivityManager.Web/Models/ActivityType.cs
namespace ActivityManager.Web.Models
{
    public class ActivityType
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = null!;
        public ICollection<Activity> Activities { get; } = new List<Activity>(); //1:N

    }
}

ActivityManager.Web/Models/ErrorViewModel.cs
namespace ActivityManager.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ActivityManager.Web/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ActivityManager.Web.Data;
using ActivityManager.Web.Models;

namespace ActivityManager.Web.Controllers
{
    public class ActivitiesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ActivityManagerWebContext _context;
        ActivityType _activityType = new();

        public ActivitiesController(ActivityManagerWebContext context, ILogger<HomeController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: Activities
        public async Task<IActionResult> Index(Guid id)
        {
            if (_context.ActivityType == null)
            {
                return NotFound();
            }

            var activityType = await _context.ActivityType
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (activityType == null)
            {
                return NotFound();
            }

            return View(activityType);
        }

        [HttpPost]
        public async Task<IActionResult> Start(Guid id)
        {
            var activity = new Activity
            {
                Id = Guid.NewGuid(),
                StartTime = DateTime.Now,
                ActivityTypeId = id
            };
            _context.Add(activity);
            await _context.SaveChangesAsync();

            var activityType = await _context.ActivityType
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);

            return View("Index", activityType);
        }

        [HttpPost]
        public async Task<IActionResult> Stop(Guid id)
        {

            if (_context.Activity == null)
            {
                return NotFound();
            }


            var activityType = await _context.ActivityType
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);

            var activity = ReturnOpenActivity(activityType);

            if (activity == null)
            {
                return NotFound();
            }

            activity.EndTime = DateTime.Now;
            TimeSpan d = (TimeSpan)(activity.EndTime - activity.StartTime);
            activity.Duration = Math.Round(d.TotalMinutes, 2);

            await _context.SaveChangesAsync();

            return View("Index", activityType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Submit(Guid id, string note)
        {
            if (_context.Activity == null)
            {
                return NotFound();
            }

            var activityType = await _context.ActivityType
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);

            var activity = ReturnOpenActivity(activityType);

            if (activity == null)
            {
                return NotFound();
            }

            activity.Note = note;
            activity.IsSaved = true;

            await _context.SaveChangesAsync();

            return View("Index", activityType);
        }

        Activity? ReturnOpenActivity(ActivityType at)
        {
            foreach (var a in at.Activities)
            {
                if (!a.IsSaved)
                {
                    return a;
                }
            }
            return null;
        }

        // GET: Activities/Delete/5
        public async Task<IActionResult> Delete(Guid id, Guid typeId)
        {
            if (_context.Activity == null)
            {
                return NotFound();
            }

            var activity = await _context.Activity.FindAsync(id);

            if (activity == null)
            {
                return NotFound();
            }

            _context.Activity.Remove(activity);
            await _context.SaveChangesAsync();

            var activityType = await _context.ActivityType
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == typeId);

            return View("Index", activityType);
        }

        private bool ActivityExists(Guid id)
        {
          return (_context.Activity?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ActivityManager.Web/Controllers/HomeController.cs
using ActivityManager.Web.Data;
using ActivityManager.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace ActivityManager.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ActivityManagerWebContext _context;

        public HomeController(ActivityManagerWebContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.ActivityType != null ?
                        View(await _context.ActivityType.ToListAsync()) :
                        Problem("Entity set 'ActivityManagerWebContext.ActivityType'  is null.");
        }

        [HttpPost]
        public async Task<IActionResult> Create(string activityNameInput)
        {
            if(activityNameInput != null)
            {
                ActivityType activityType = new()
                {
                    Id = Guid.NewGuid(),
                    Name = activityNameInput
                };
                _context.Add(activityType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.ActivityType == null)
            {
                return NotFound();
            }

            var activityType = await _context.ActivityType
                .Include(m => m.Activities)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (activityType == null)
            {
                return NotFound();
            }

            return View(activityType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.ActivityType == null)
            {
                return Problem("Entity set 'ActivityManagerWebContext.ActivityType'  is null.");
            }
            var activityType = await _context.ActivityType.FindAsync(id);
            if (activityType != null)
            {
                _context.ActivityType.Remove(activityType);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return base.View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ActivityManager.Web/Views/Activities/Index.cshtml
@model ActivityManager.Web.Models.ActivityType

@{
    ViewData["Title"] = "Index";
}

@functions{
    Activity? ReturnOpenActivity(ActivityType at)
    {
        foreach(var a in at.Activities)
        {
            if (!a.IsSaved)
            {
                return a;
            }
        }
        return null;
    }
}

<div>
    <h1>@Model.Name</h1>
    <div class="row text-center">
        <div class="col-md-auto">
            <ul id="activities-list">
                @{Model.Activities.OrderBy(a => a.StartTime);}
                @foreach (var item in Model.Activities)
                {
                    <li class="mb-2 p-1 bg-light bg-opacity-10
                            border border-warning rounded-end
                            d-block-flex">
                        <div class="d-block">
                            <div class="d-inline-flex">
                                <p>@item.StartTime   |</p>
                                <p class="ms-auto">   @item.EndTime</p>
                            </div>
                            @if (item.Duration != null)
                            {
                                <p>Duration: @item.Duration</p>
                            }
                        </div>
                        <p>@item.Note</p>
                        <a class="p-1 rounded text-danger"
                           asp-action="Delete" asp-route-id="@item.Id" asp-route-typeId="@Model.Id">
                            [Delete]
                        </a>
                    </li>
                }
            </ul>
        </div>
        <div class="col-md-auto">
            @if (Model.Activities.Count == 0 || ReturnOpenActivity(Model) == null)
            {
                <h4>Start new Activity</h4>
                <form asp-action="Start">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Start" class="btn btn-primary" />
                </form>
            }
            else if (ReturnOpenActivity(Model).EndTime == null)
            {
                <h4>Stop ongoing Activity</h4>
                <p>Start: @Model.Activities.First().StartTime</p>
                <form asp-action="Stop">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Stop" class="btn btn-primary" />
                </form>
            }
            else
            {
                <h4>Submit ongoing Activity</h4>
                <p>Start: @Model.Activities.First().StartTime</p>
                <p>Stop: @Model.Activities.First().EndTime</p>
                <p>Duration: @Model.Activities.First().Duration</p>
                <form asp-action="Submit">
                    <input name="note" type="text" class="form-control mb-3"
                           placeholder="Add note (optional)">
                    <input type="hidden" asp-for="Id" />
                    <input type="submit" value="Submit" class="btn btn-primary" />
                </form>
            }
        </div>
    </div>
</div>

ActivityManager.Web/Views/Home/Delete.cshtml
@model ActivityManager.Web.Models.ActivityType

@{
    ViewData["Title"] = "Delete";
}


<h3>Are you sure you want to delete @Model.Name?</h3>
<h4>It has @Model.Activities.Count recorded activities.</h4>
 
<div d-flex>
    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirm delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to main menu</a>
    </form>
</div>

ActivityManager.Web/Views/Home/Index.cshtml
@model IEnumerable<ActivityManager.Web.Models.ActivityType>

@{
    ViewData["Title"] = "Home Page";
}

<template id="listitemTemplate">
    <li data-activityName 
        class="mb-2 p-1 bg-light bg-opacity-10 
            border border-warning rounded-end
            d-flex">
        <a id="nameLink" class="nav-line d-inline-flex p-2" asp-area="" 
            asp-controller="Home" asp-action="ListItemClick">
                Activity
        </a>
        <button type="button"
                class="btn btn-danger d-inline-flex ms-auto"
            onclick="clickDeleteActivity()">
                Delete
        </button>
    </li>
</template>

<div>
    <div class="row text-center">
        <div class="col-md-auto">
            <ul id="activities-list">
                @foreach (var item in Model)
                {
                    <li class="mb-2 p-1 bg-light bg-opacity-10
                            border border-warning rounded-end
                            d-flex">
                        <a id="nameLink" class="nav-line d-inline-flex p-2"
                            asp-controller="Activities" asp-action="Index"
                            asp-route-id="@item.Id">
                            @item.Name
                        </a>
                        <a class=" d-inline-flex ms-auto align-self-center
                                p-1 rounded text-danger"
                           asp-action="Delete" asp-route-id="@item.Id">
                           [Delete]
                        </a>
                    </li>
                }
            </ul>
        </div>
        <div class="col-md-auto">
            <h4>Create new ActivityType</h4>
            <form asp-action="Create">
                <input name="activityNameInput" type="text" class="form-control mb-3" 
                    placeholder="Activity name">
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>

<script src="~/js/home.js" asp-append-version="true"></script>

ActivityManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ActivityManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ActivityManager.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ActivityManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container d-flex justify-content-center">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ActivityManager.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>